# Generated by Django 4.2.1 on 2024-02-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('author', models.CharField(max_length=100)),
                ('upvotes', models.PositiveBigIntegerField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-upvotes', 'time_added'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.PositiveBigIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
            options={
                'ordering': ['-upvotes'],
            },
        ),
    ]
