# Generated by Django 4.2.1 on 2024-04-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='upvotes',
            field=models.PositiveBigIntegerField(blank=True),
        ),
    ]
